name: Approve And Merge Dependabot PR

on:
  pull_request:

jobs:
  gradle-check:
    name: Approve And Merge Dependabot PR
    uses: interlok-tooling/reusable-workflows/.github/workflows/approve-merge-dependabot-pr.yml@main
