name: Gradle Publish

on:
  push:
    branches:
    - develop
  schedule:
    - cron: 0 3 * * * # Daily 3 a.m.

jobs:
  gradle-publish:
    uses: interlok-tooling/gradle-publish/.github/workflows/action.yml@main
